lib/todo_web/router.ex
defmodule TodoWeb.Router do
  use TodoWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TodoWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/session/new", SessionController, :new)
    post("/session/create", SessionController, :create)
    delete("/sign_out", SessionController, :delete)

    # registration
    resources("/registrations", RegistrationController, only: [:new, :create])
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoWeb do
  #   pipe_through :api
  # end
end

lib/todo/application.ex
defmodule Todo.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Todo.Repo, []),
      # Start the endpoint when the application starts
      supervisor(TodoWeb.Endpoint, []),
      # Start your own worker by calling: Todo.Worker.start_link(arg1, arg2, arg3)
      # worker(Todo.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Todo.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TodoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/todo/repo.ex
defmodule Todo.Repo do
  use Ecto.Repo, otp_app: :todo

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/todo/todos/todo.ex
defmodule Todo.Todos.Todo do
  use Ecto.Schema
  import Ecto.Changeset


  schema "todos" do
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(todo, attrs) do
    todo
    |> cast(attrs, [:name])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

lib/todo/todos/todo_item.ex
defmodule Todo.Todos.TodoItem do
  use Ecto.Schema
  import Ecto.Changeset
  alias Todo.Todos.Todo

  schema "todo_items" do
    field(:done, :boolean, default: false)
    field(:name, :string)
    belongs_to(:todo, Todo)

    timestamps()
  end

  @doc false
  def changeset(todo_item, attrs) do
    todo_item
    |> cast(attrs, [:name, :done])
    |> validate_required([:name, :done])
    |> unique_constraint(:name)
  end
end

lib/todo_web/controllers/page_controller.ex
defmodule TodoWeb.PageController do
  use TodoWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/todo_web/controllers/registration_controller.ex
defmodule TodoWeb.RegistrationController do
  use TodoWeb, :controller
  alias Todo.Auth.User

  def new(conn, _params) do
    changeset = User.registration_changeset(%User{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"registration" => registration_params}) do
    case User.register(registration_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have successfully signed up!")
        |> redirect(to: page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    conn
    |> User.sign_out()
    |> redirect(to: page_path(conn, :index))
  end
end

lib/todo_web/controllers/session_controller.ex
defmodule TodoWeb.SessionController do
  use TodoWeb, :controller
  alias Todo.Auth.User

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    case User.sign_in(email, password) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have successfully signed in!")
        |> redirect(to: page_path(conn, :index))

      {:error, reason} ->
        conn
        |> put_flash(:error, "Invalid Email or Password")
        |> render("new.html")
    end
  end

  def delete(conn, _params) do
    conn
    |> User.sign_out()
    |> redirect(to: page_path(conn, :index))
  end
end

lib/todo_web/controllers/todo_controller.ex
defmodule TodoWeb.TodoController do
  use TodoWeb, :controller

  def new(conn, _params) do
  end
end

lib/todo_web/views/error_view.ex
defmodule TodoWeb.ErrorView do
  use TodoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/todo_web/views/layout_view.ex
defmodule TodoWeb.LayoutView do
  use TodoWeb, :view
end

lib/todo_web/views/page_view.ex
defmodule TodoWeb.PageView do
  use TodoWeb, :view
end

lib/todo_web/views/registration_view.ex
defmodule TodoWeb.RegistrationView do
  use TodoWeb, :view
end

lib/todo_web/views/session_view.ex
defmodule TodoWeb.SessionView do
  use TodoWeb, :view
end

lib/todo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Todo!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
          </ul>
        </nav>

        <%= if Todo.Auth.User.user_signed_in?(@conn) do %>
          <nav class="my-2 my-md-0 mr-md-3">
            Signed in as: <strong><%= Todo.Auth.User.current_user(@conn).username %></strong>
          </nav>
          <%= link "Sign Out", to: session_path(@conn, :delete), method: :delete, class: "btn btn-outline-primary" %>
        <% else %>
          <%= link "Sign In", to: session_path(@conn, :new), class: "btn btn-outline-primary" %>
          <%= link "Sign Up", to: registration_path(@conn, :new), class: "btn btn-outline-primary ml-md-3" %>
        <% end %>

      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/todo_web/templates/page/index.html.eex
<div id="vue-root">
<Todo
    :path="<%= page_path(@conn, :index) %>"
>
</Todo>
</div>

lib/todo_web/templates/session/new.html.eex
<div class="auth-form-wrapper">
  <%= form_for @conn, session_path(@conn, :create), [as: :session, class: "form-signin"], fn f -> %>
    <div class="text-center mb-4">
      <h1 class="h3 mb-3 font-weight-normal">Sign In</h1>
    </div>

    <div class="form-label-group">
      <%= text_input f, :email, class: "form-control", placeholder: "Email address", required: true, autofocus: true %>
      <%= label f, :email, "Email address", class: "control-label" %>
    </div>

    <div class="form-label-group">
      <%= password_input f, :password, class: "form-control", placeholder: "Password", required: true %>
      <%= label f, :password, class: "control-label" %>
    </div>

    <%= submit "Sign in", class: "btn btn-lg btn-primary btn-block" %>
  <% end %>
</div>